In [1]:
from __future__ import print_function

In [2]:
import torch

In [6]:
# create 5x3 matrix
torch.empty(5,3)

tensor([[8.0705e+17, 1.1703e-19, 1.5637e-01],
        [7.3899e+20, 5.0782e+31, 4.2964e+24],
        [1.7443e+28, 3.9216e-08, 3.9552e-14],
        [1.3563e-19, 1.8578e-01, 1.1722e-19],
        [5.0746e+31, 7.5338e+28, 6.1687e+16]])

In [11]:
torch.rand(5,3)

tensor([[0.0414, 0.8817, 0.4231],
        [0.2619, 0.3122, 0.7252],
        [0.2536, 0.9197, 0.0501],
        [0.2386, 0.3615, 0.9522],
        [0.5918, 0.9620, 0.9000]])

In [14]:
torch.zeros(5,3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [16]:
x = torch.tensor([5.5, 3])

In [17]:
x = x.new_ones(5, 3, dtype=torch.double)
print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [20]:
# override dtype, but result will have same size
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.5942, 0.6442, 0.2638],
        [0.9067, 0.2267, 0.6155],
        [0.4807, 0.6563, 0.6469],
        [0.0709, 0.7850, 0.5791],
        [0.4282, 0.3716, 0.9798]])


In [21]:
x.size() # a tuple supports all tuple operations

torch.Size([5, 3])

In [23]:
y = torch.rand(5,3)
x+y

tensor([[1.1770, 0.9794, 0.8604],
        [1.3617, 0.3348, 1.5361],
        [1.0391, 1.2169, 0.8958],
        [0.6811, 1.5806, 1.1482],
        [0.6444, 0.9081, 1.5602]])

In [24]:
print(torch.add(x, y))

tensor([[1.1770, 0.9794, 0.8604],
        [1.3617, 0.3348, 1.5361],
        [1.0391, 1.2169, 0.8958],
        [0.6811, 1.5806, 1.1482],
        [0.6444, 0.9081, 1.5602]])


In [26]:
result = torch.empty(5,3)
## provide an output tensor
torch.add(x, y, out=result)
print(result)

tensor([[1.1770, 0.9794, 0.8604],
        [1.3617, 0.3348, 1.5361],
        [1.0391, 1.2169, 0.8958],
        [0.6811, 1.5806, 1.1482],
        [0.6444, 0.9081, 1.5602]])


In [27]:
y.add_(x)
print(y)

tensor([[1.1770, 0.9794, 0.8604],
        [1.3617, 0.3348, 1.5361],
        [1.0391, 1.2169, 0.8958],
        [0.6811, 1.5806, 1.1482],
        [0.6444, 0.9081, 1.5602]])


In [29]:
y[:, 1]

tensor([0.9794, 0.3348, 1.2169, 1.5806, 0.9081])

In [31]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0423])
1.0422711372375488


In [33]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [34]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [35]:
import numpy as np

In [36]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
if torch.cuda.is_available():
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([2.0423], device='cuda:0')
tensor([2.0423], dtype=torch.float64)
