"autograd" package provides automatic differentiation for all operations on "Tensor" object. Backpropagation defines how the code is run.

When ".requires_grad" option in Tensor object is True, it starts to track all operations on it. "backward()" will compute all the gradients automatically.

In [1]:
import torch
import numpy as np

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
print(y.grad_fn)

In [8]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [9]:
a = torch.rand(2,2)
a = ((a * 3) / (a - 1))
print (a.requires_grad)
a.requires_grad_(True)
print (a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [22]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 100:
    y = y * 2
print(y)

tensor([-62.3217, -88.3492, 118.5020], grad_fn=<MulBackward0>)


In [23]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([2.5600e+01, 2.5600e+02, 2.5600e-02])
